Add linting for server

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -7,9 +7,19 @@ cd client && npm run lint
 linter_exit_code=$?
 if [ $linter_exit_code -ne 0 ]
 then
-  echo "${RED} ❌ Linter errors have occurred ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
+  echo "${RED} ❌ Linter errors found in client ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
   exit 1
 else
-  echo "${GREEN} ✔ Eslint did not find any errors [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
+  echo "${GREEN} ✔ Eslint did not find any errors in client [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
+  exit 0
+fi
+cd ../server && npm run lint
+linter_exit_code=$?
+if [ $linter_exit_code -ne 0 ]
+then
+  echo "${RED} ❌ Linter errors found in client ( ͡ಥ ͜ʖ ͡ಥ)${NC}"
+  exit 1
+else
+  echo "${GREEN} ✔ Eslint did not find any errors in client [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]${NC}"
   exit 0
 fi
